import { useEffect, useState } from "react"
import { getToken, setToken } from "./api"
import { Approvals } from "./pages/Approvals"
import { Dashboard } from "./pages/Dashboard"
import { FlowBuilder } from "./pages/FlowBuilder"
import { GraphPage } from "./pages/Graph"
import { JobDetail } from "./pages/Job"

// Hash router: #/ #/graph #/jobs/<id> #/flows #/approvals — no router dep.
function useHash(): string {
  const [hash, setHash] = useState(window.location.hash || "#/")
  useEffect(() => {
    const onChange = () => setHash(window.location.hash || "#/")
    window.addEventListener("hashchange", onChange)
    return () => window.removeEventListener("hashchange", onChange)
  }, [])
  return hash
}

function TokenGate({ onSet }: { onSet: () => void }) {
  const [value, setValue] = useState("")
  return (
    <div className="token-gate panel">
      <h2>Talon Console</h2>
      <p className="muted">
        Paste the <code>[gateway] api_token</code> from{" "}
        <code>~/.talon/config.toml</code> (generated by <code>talon init</code>
        ).
      </p>
      <div className="row">
        <input
          type="password"
          value={value}
          placeholder="talon_…"
          onChange={(e) => setValue(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && value.trim()) {
              setToken(value.trim())
              onSet()
            }
          }}
        />
        <button
          className="primary"
          onClick={() => {
            if (value.trim()) {
              setToken(value.trim())
              onSet()
            }
          }}
        >
          Save
        </button>
      </div>
    </div>
  )
}

export function App() {
  const hash = useHash()
  const [hasToken, setHasToken] = useState(() => getToken() !== "")

  if (!hasToken) {
    return <TokenGate onSet={() => setHasToken(true)} />
  }

  const jobMatch = hash.match(/^#\/jobs\/(.+)$/)
  const page = jobMatch ? (
    <JobDetail id={decodeURIComponent(jobMatch[1])} />
  ) : hash.startsWith("#/graph") ? (
    <GraphPage />
  ) : hash.startsWith("#/flows") ? (
    <FlowBuilder />
  ) : hash.startsWith("#/approvals") ? (
    <Approvals />
  ) : (
    <Dashboard />
  )

  const link = (to: string, label: string, active: boolean) => (
    <a href={to} className={active ? "active" : ""}>
      {label}
    </a>
  )

  return (
    <>
      <nav>
        <span className="brand">🦅 talon</span>
        {link("#/", "Dashboard", hash === "#/" || hash === "")}
        {link("#/graph", "Graph", hash.startsWith("#/graph"))}
        {link("#/flows", "Flow Builder", hash.startsWith("#/flows"))}
        {link("#/approvals", "Approvals", hash.startsWith("#/approvals"))}
        <span style={{ flex: 1 }} />
        <button
          onClick={() => {
            setToken("")
            setHasToken(false)
          }}
        >
          token
        </button>
      </nav>
      <main>{page}</main>
    </>
  )
}
